# Generated by Django 6.0.6 on 2026-06-16 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0002_product_created_at_product_discount_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="aechived",
            field=models.BooleanField(default=False),
        ),
    ]
