# Generated by Django 6.0.6 on 2026-06-16 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0003_product_aechived"),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("delivery_address", models.TextField(blank=True, null=True)),
                ("promocode", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
