# Generated by Django 6.0.6 on 2026-06-16 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0005_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="products",
            field=models.ManyToManyField(related_name="orders", to="shopapp.product"),
        ),
    ]
