# Generated by Django 6.0.6 on 2026-06-17 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0007_alter_product_options_alter_product_discount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="aechived",
            new_name="archived",
        ),
    ]
