# Generated by Django 6.0.6 on 2026-06-28 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0009_alter_product_discount_alter_product_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="receipt",
            field=models.FileField(null=True, upload_to="orders/receipts"),
        ),
    ]
