# Generated by Django 6.0.6 on 2026-06-28 09:50

import shopapp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0010_order_receipt"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="prewiew",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=shopapp.models.product_prewiew_directory_path,
            ),
        ),
    ]
