# Generated by Django 6.0.6 on 2026-07-08 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shopapp", "0012_productimage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={"verbose_name": "Order"},
        ),
        migrations.AlterModelOptions(
            name="product",
            options={"ordering": ["name", "price"], "verbose_name": "Product"},
        ),
    ]
