# Generated by Django 6.0.6 on 2026-08-19 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="article",
            old_name="pub_data",
            new_name="pub_date",
        ),
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="article",
            name="title",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="author",
            name="bio",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=20),
        ),
    ]
