# Generated by Django 6.0.6 on 2026-08-25 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blogapp", "0002_rename_pub_data_article_pub_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="content",
            field=models.TextField(blank=True, null=True),
        ),
    ]
