"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 6.0.6.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
from django.utils.translation import gettext_lazy as _
from pathlib import Path

from os import getenv
import logging.config
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# для развертыванмя проекта с mysqlite
DATABASE_DIR = BASE_DIR / "database"
DATABASE_DIR.mkdir(exist_ok=True)



# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
#SECRET_KEY = "django-insecure-gdtd08)7woez(hs&bpf4i&mqn&15_p13kql3i&ncljvldy+n)="


# для env.template
SECRET_KEY = getenv(
    "DJANGO_SECRET_KEY",
    "django-insecure-gdtd08)7woez(hs&bpf4i&mqn&15_p13kql3i&ncljvldy+n)=",

)

# SECURITY WARNING: don't run with debug turned on in production!

#DEBUG = True
# для env.template
DEBUG = getenv("DJANGO_DEBUG","0") == "1"



# для docker
ALLOWED_HOSTS = [
    "83.217.223.6",
    "0.0.0.0",
    '127.0.0.1'
] + getenv("DJANGO_ALLOWED_HOSTS","").split(",")


# для профелирования

INTERNAL_IPS = [
    '127.0.0.1',
]
# для docker
if DEBUG:
    import socket
    hostname, _,ips = socket.gethostbyname_ex(socket.gethostname())
    INTERNAL_IPS.append("10.0.2.2")
    INTERNAL_IPS.extend(
        [ip[: ip.rfind(".")] + ".1" for ip in ips])


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",

    "rest_framework",

            # для профелирования
    "debug_toolbar",
    

    "shopapp.apps.ShopappConfig",
    "requestdataapp.apps.RequestdataappConfig",
    "myauth.apps.MyauthConfig",
    "blogapp.apps.BlogappConfig",
    "myapiapp.apps.MyapiappConfig",

    "django.contrib.admindocs",
    "django_filters"


    
]

MIDDLEWARE = [
    #"django.middleware.cache.UpdateCacheMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",

    "requestdataapp.middlewares.set_useragent_on_request_middleware",
    "requestdataapp.middlewares.CountRequestMiddlewarw",

    "django.middleware.locale.LocaleMiddleware",
    "django.contrib.admindocs.middleware.XViewMiddleware",

    # для профелирования
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    #кеширование
    #"django.middleware.cache.FetchFromCacheMiddleware",



  
]

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.Argon2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
    "django.contrib.auth.hashers.PBKDF2SHA1PasswordHasher",
    "django.contrib.auth.hashers.BCryptSHA256PasswordHasher",
]



ROOT_URLCONF = "mysite.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mysite.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

#DATABASES = {
#    "default": {
#        "ENGINE": "django.db.backends.sqlite3",
#        "NAME": BASE_DIR / "db.sqlite3",
#    }
#}

# для развертывания проекта с mqsqlite
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": DATABASE_DIR / "db.sqlite3",
    }
}


CACHES = {
    'default': {
        "BACKEND": "django.core.cache.backends.dummy.DummyCache",
        # лучше нижнее
        #"BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": "/var/tmp/django_cache",
       # "LOCAtion": "c:/foo/bar",
    },
}
CACHE_MIDDLWARE_SECONDS = 200

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/


REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE":10,
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ]
}



LANGUAGE_CODE = "en-us"


TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# for localization
USE_L10N = True
LOCALE_PATHS = [
    BASE_DIR / 'locale/'
]
#LANGUAGES = [
#    ("en", _("English")),
 #   ("ru", _("Russian"))
#]



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "static/"
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'uploads'
# DEFAULT_FILE_STORAGE = 




from django.urls import reverse_lazy
# куда перенаправлять пользователя после входа LoginView
LOGIN_REDIRECT_URL = reverse_lazy('myauth:about_me_url')
# куда перенаправлять для входа
LOGIN_URL = reverse_lazy('myauth:login')

# для docker_compose

LOGLEVEL = getenv("DJANGO_LOGLEVEL","info").upper()


LOGFILE_NAME = BASE_DIR / 'log.txt'
LOGFILE_SIZE = 400
#LOGFILE_SIZE = 1 * 1024 * 1024
LOGFILE_COUNT = 3

LOGGING = {
    "version":1,
    "disable_existing_loggers":False,
    "formatters": {
        "verbose":{
            "format":"%(asctime)s [%(levelname)s] %(name)s %(message)s"
        }
    },
    "handlers":{
        "console":{
            "class": "logging.StreamHandler",
            "formatter":"verbose",
        },
        "logfile":{
            "class": "logging.handlers.RotatingFileHandler",
            "filename":LOGFILE_NAME,
            "maxBytes":LOGFILE_SIZE,
            "backupCount":LOGFILE_COUNT,
            "formatter":"verbose",
        },
    },
    "root":{
        "handlers": ['console','logfile'],
        "level":"INFO"
    }
}


# LOGGING = {
#    'version':1,
#    'filters':{
#        'requaire_debug_true':{
#            '()':'django.utils.log.RequireDebugTrue'
#        },
#    },
#    'handlers':{
#        'console':{
#            'level':'DEBUG',
#            'filters':['requaire_debug_true'],
#            'class':'logging.StreamHandler',
#        },
#    },
#    'loggers':{
#        'django.db.backends':{
#            'level':'DEBUG',
#            'handlers':['console'],
#        }
#    },
#}


# для docker-compose
logging.config.dictConfig({
    'version':1,
    "disable_existing_loggers":False,
    "formatters":{
        'console':{
            "format":"%(asctime)s %(levelname)s %(name)s %(lineno)s %(module)s %(massage)s"
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "console",
        },
    },
    "loggers":{
        "":{
            "level":LOGLEVEL,
            "handlers":[
                "console",
            ],
        },
    },
})